---
# Compute Resources and there credentials to connect to them for cleanup
AWS:
  AUTH:
    ACCESS_KEY: $AWS_ACCESS_KEY
    SECRET_KEY: $AWS_SECRET_KEY
    REGIONS: ["all"]
  CRITERIA:
    VM:
      # The VM to be deleted with prepend string, e.g VM name that starts with 'test'
      DELETE_VM: ''
      # Number of minutes the deletable VM should be allowed to live, e.g 120 minutes = 2 Hours
      SLA_MINUTES: 7200
    DISC:
      UNASSIGNED: True
    NIC:
      UNASSIGNED: True
    PUBLIC_IP:
      UNASSIGNED: True
    STACKS:
      # The CloudFormation to be deleted with prepend string, e.g stack name that starts with 'test'
      DELETE_STACK: 'test'
      # Number of minutes the deletable CloudFormation should be allowed to live, e.g 120 minutes = 2 Hours
      SLA_MINUTES: 120
  EXCEPTIONS:
    VM:
      # VM names that would be skipped from cleanup
      VM_LIST: []
      # VMs that would be stopped from current running state
      STOP_LIST: []
    STACKS:
      # CloudFormations names that would be skipped from cleanup
      STACK_LIST: []